class LishiTrainingModel {
  final String modelName;
  final String vedioLink;

  LishiTrainingModel({required this.modelName, required this.vedioLink});
}

List<LishiTrainingModel> lishiTrainingData = [
  LishiTrainingModel(modelName: 'Fo38', vedioLink: 'https://youtu.be/i38Lw7aPBqo'),
  LishiTrainingModel(modelName: 'Hu101', vedioLink: 'https://youtu.be/CV8ChK9Hx5I'),
  LishiTrainingModel(modelName: 'Nsn14', vedioLink: 'https://youtu.be/cdcxLbnzZZ0'),
  LishiTrainingModel(modelName: 'Gm39', vedioLink: 'https://youtu.be/ztldnxtLsUM'),
  LishiTrainingModel(modelName: 'Toy43at', vedioLink: 'https://youtu.be/K4A22OuDzcw'),
  LishiTrainingModel(modelName: 'Hu92', vedioLink: 'https://youtu.be/CZkKQSYYJHI'),
  LishiTrainingModel(modelName: 'Hu100', vedioLink: 'https://youtu.be/wH3dKddIqdI'),
  LishiTrainingModel(modelName: 'Gm37', vedioLink: 'https://youtu.be/tYGjfLWUlyk'),
  LishiTrainingModel(modelName: 'Mit6 & Mit9', vedioLink: 'https://youtu.be/D8MPE2Mm9hY'),
  LishiTrainingModel(modelName: 'Cy24', vedioLink: 'https://youtu.be/BPaj_vwVy54'),
  LishiTrainingModel(modelName: 'B111', vedioLink: 'https://youtu.be/mXYy2ivSk10'),
  LishiTrainingModel(modelName: 'Hy14r & Hy15', vedioLink: 'https://youtu.be/Qx1v5Gm6Flw'),
  LishiTrainingModel(modelName: 'Toy48', vedioLink: 'https://youtu.be/ekvl7b9HJP0'),
  LishiTrainingModel(modelName: 'Hu64', vedioLink: 'https://youtu.be/2EZojqdaFQk'),
  LishiTrainingModel(modelName: 'Toy40', vedioLink: 'https://youtu.be/-l_0mTBFaTM'),
  LishiTrainingModel(modelName: 'Va2t', vedioLink: 'https://youtu.be/P0oM_0JMMz4'),
  LishiTrainingModel(modelName: 'Maz24', vedioLink: 'https://youtu.be/vy3pdkyAAQc'),
  LishiTrainingModel(modelName: 'Hu66', vedioLink: 'https://youtu.be/5iYtcveObxs'),
  LishiTrainingModel(modelName: 'Kw1', vedioLink: 'https://youtu.be/G46m1X9VT2M'),
  LishiTrainingModel(modelName: 'Sc1', vedioLink: 'https://youtu.be/llRYbTxbunU'),
  LishiTrainingModel(modelName: 'Kw5', vedioLink: 'https://youtu.be/6KkBcR6cOgE'),
  LishiTrainingModel(modelName: 'Sc4', vedioLink: 'https://youtu.be/MobP0raqms4'),
  LishiTrainingModel(modelName: 'M1 & Ms2', vedioLink: 'https://youtu.be/J8GhiOdiaSU'),
  LishiTrainingModel(modelName: 'Am5', vedioLink: 'https://youtu.be/erCwuND4nwc'),
  LishiTrainingModel(modelName: 'Yale 6b', vedioLink: 'https://youtu.be/Ev4g002GO0w'),
  LishiTrainingModel(modelName: 'Abus 1', vedioLink: 'https://youtu.be/VrkNfQ7mrBg'),
  LishiTrainingModel(modelName: 'Hon66', vedioLink: 'https://youtu.be/vd9U0aJ47b4'),
  LishiTrainingModel(modelName: 'Hon58r', vedioLink: 'https://youtu.be/5TLQt9YFx3Q'),
  LishiTrainingModel(modelName: 'Sip22', vedioLink: 'https://youtu.be/V8ItS8VYWh8'),
  LishiTrainingModel(modelName: 'Tibbe', vedioLink: 'https://youtu.be/_C_V9ba6G_k'),
  LishiTrainingModel(modelName: 'Dat17', vedioLink: 'https://youtu.be/LRXBU5f0ddI'),
  LishiTrainingModel(modelName: 'Mit11', vedioLink: 'https://youtu.be/Yz4FstvBjzk'),
  LishiTrainingModel(modelName: 'Kw16', vedioLink: 'https://youtu.be/k2kR3DDKcDQ'),
  LishiTrainingModel(modelName: 'Be2', vedioLink: 'https://youtu.be/PDJ6N-II7Yg'),
  LishiTrainingModel(modelName: 'Hu58', vedioLink: 'https://youtu.be/3STunIeLeJM'),
  LishiTrainingModel(modelName: 'Sz14', vedioLink: 'https://youtu.be/bbeOQu8KrOc'),
  LishiTrainingModel(modelName: 'Toy38r', vedioLink: 'https://youtu.be/N78_xiJoqQc'),
  LishiTrainingModel(modelName: 'Isu5', vedioLink: 'https://youtu.be/JUFcO4HUjWk'),
  LishiTrainingModel(modelName: 'Kw14', vedioLink: 'https://youtu.be/cEwODGDdMgA'),
  LishiTrainingModel(modelName: 'Hd74', vedioLink: 'https://youtu.be/f4LH3bACMKk'),
  LishiTrainingModel(modelName: 'S123 & C123', vedioLink: 'https://youtu.be/9XHlDHCoK_4'),
  LishiTrainingModel(modelName: 'Ne38', vedioLink: 'https://youtu.be/EUzfOEL_VNY'),
  LishiTrainingModel(modelName: 'Ne66', vedioLink: 'https://youtu.be/4O8cVv0QJCI'),
  LishiTrainingModel(modelName: 'Hu162(9)', vedioLink: 'https://youtu.be/fW1q8z2aqKI'),
  LishiTrainingModel(modelName: 'Hu162(10)', vedioLink: 'https://youtu.be/nsrIWeB4pTo'),
  LishiTrainingModel(modelName: 'Hy16', vedioLink: 'https://youtu.be/AUGt4zKw5lU'),
  LishiTrainingModel(modelName: 'Dw04r', vedioLink: 'https://youtu.be/-4Or0Hb06nE'),
  LishiTrainingModel(modelName: 'Gm45', vedioLink: 'https://youtu.be/jbpUnAPyFvk'),
  LishiTrainingModel(modelName: 'Hon70', vedioLink: 'https://youtu.be/wz7so3NvHco'),
  LishiTrainingModel(modelName: 'Hu198', vedioLink: 'https://youtu.be/dkNLDFrF16U'),
];